### PR TITLE
PA is now fully ported to 1.11!

### PR DESCRIPTION
**Pull request by Psycho-Ray**
Hey o/

Vanhal seemed to be too busy to do port Progressive Automation right now, so I decided to show how much I loved this mod :]

I've already did a few tests, and everything seem to be in place. I dived deep into the code to make sure I've changed everything I needed to, but who knows, right? Please, play it a lot and report any bugs :~]

By the way, it might be wiser to put it in another branch, but I don't really know how to do it.

### CODE REVIEW

**Comment by Vanhal** [comment]
I'll merge and compile in the morning! Thanks for your help

**Comment by Psycho-Ray** [comment]
The Lang files require some renaming. I'll finish it soon and commit here

**Comment by Psycho-Ray** [comment]
The Wrench shift+right click is not working. I've been trying to fix it for hours =/

**Comment by Vanhal** [comment]
I feel like that wasn't working properly in 1.10 either because of the way that right clicking was changed...

**Comment by Psycho-Ray** [comment]
I tried to learn from Chest Transporter mod source code, but it's above my capabilities. Sorry =/

**Pull request merged**
